In [141]:
import numpy as np

In [142]:
multi_array = [[1,2,3],[4,5,6],[7,8,9]]
multi_array

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [143]:
matrix = np.array(multi_array)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [144]:
type(matrix)

numpy.ndarray

In [145]:
np.arange(5, 25, 2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [146]:
# Rows x Columns
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [147]:
np.linspace(0, 23, num=4)

array([ 0.        ,  7.66666667, 15.33333333, 23.        ])

In [148]:
np.linspace(1, 12, 13)

array([ 1.        ,  1.91666667,  2.83333333,  3.75      ,  4.66666667,
        5.58333333,  6.5       ,  7.41666667,  8.33333333,  9.25      ,
       10.16666667, 11.08333333, 12.        ])

In [149]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [150]:
# Random number [0.0, 1.0)
np.random.rand(2,3,4)

array([[[0.78517596, 0.19967378, 0.51423444, 0.59241457],
        [0.04645041, 0.60754485, 0.17052412, 0.06505159],
        [0.94888554, 0.96563203, 0.80839735, 0.30461377]],

       [[0.09767211, 0.68423303, 0.44015249, 0.12203823],
        [0.49517691, 0.03438852, 0.9093204 , 0.25877998],
        [0.66252228, 0.31171108, 0.52006802, 0.54671028]]])

In [151]:
# Standard normal distribution - mean = 0, variance = 1
np.random.randn(2,3,4)

array([[[ 0.21863832,  0.88176104, -1.00908534, -1.58329421],
        [ 0.77370042, -0.53814166, -1.3466781 , -0.88059127],
        [-1.1305523 ,  0.13442888,  0.58212279,  0.88774846]],

       [[ 0.89433233,  0.7549978 , -0.20716589, -0.62347739],
        [-1.50815329,  1.09964698, -0.17773212, -0.41038331],
        [ 1.17971634, -0.89820794,  0.83479542,  0.29656138]]])

In [152]:
np.random.randint(5, 10, size=(2,3,4))

array([[[5, 7, 9, 7],
        [5, 9, 6, 7],
        [5, 6, 6, 8]],

       [[9, 7, 5, 8],
        [9, 8, 9, 9],
        [7, 9, 8, 9]]])

In [153]:
# hitchhiker's guide to the galaxy -> 42
np.random.seed(42)
np.random.rand(5)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [154]:
np.random.seed(42)
array = np.random.rand(25)
array

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258,
       0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497,
       0.18340451, 0.30424224, 0.52475643, 0.43194502, 0.29122914,
       0.61185289, 0.13949386, 0.29214465, 0.36636184, 0.45606998])

In [155]:
two_d_array = array.reshape(5, 5)
two_d_array

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864],
       [0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258],
       [0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497],
       [0.18340451, 0.30424224, 0.52475643, 0.43194502, 0.29122914],
       [0.61185289, 0.13949386, 0.29214465, 0.36636184, 0.45606998]])

In [156]:
array.min()

0.020584494295802447

In [157]:
array.argmin()

10

In [158]:
array.dtype

dtype('float64')

In [159]:
# (25,) to distingush from (1,25)
array.shape

(25,)

In [160]:
two_d_array.shape

(5, 5)

Coding Exercise Check-In: Creating NumPy Array

In [161]:
# TASK: Create a numpy array called myarray which consists of 101 evenly linearly spaced points between 0 and 10.
# MAKE SURE TO READ THE FULL INSTRUCTIONS ABOVE CAREFULLY, AS THE EVALUATION SCRIPT IS VERY STRICT.
# Link to Solution: https://gist.github.com/Pierian-Data/ea9c4d2fc6c98ac74af18134cd924867
# 
import numpy as np
myarray = np.linspace(0, 10, num=101)
myarray

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [162]:
# range
range = np.arange(0, 10)
range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [163]:
range[3]

3

In [164]:
range[3:6]

array([3, 4, 5])

In [165]:
range[:5]

array([0, 1, 2, 3, 4])

In [166]:
range[5:]

array([5, 6, 7, 8, 9])

In [167]:
range[:3] = 30
range

array([30, 30, 30,  3,  4,  5,  6,  7,  8,  9])

In [168]:
slice = range[:4]
slice

array([30, 30, 30,  3])

In [169]:
slice[:] = 400
slice

array([400, 400, 400, 400])

In [170]:
# NumPy Broadcasting in Action
range

array([400, 400, 400, 400,   4,   5,   6,   7,   8,   9])

In [171]:
copy = range.copy()
copy[:] = 5000

In [172]:
copy

array([5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000])

In [173]:
range

array([400, 400, 400, 400,   4,   5,   6,   7,   8,   9])

In [174]:
range = np.arange(0, 25)
range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [175]:
are_evens = range % 2 == 0
are_evens

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True])

In [176]:
range[are_evens]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [177]:
range[range % 3 == 0]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [178]:
# TASK: Use numpy to check how many rolls were greater than 2. For example if dice_rolls=[1,2,3] then the answer is 1.
# NOTE: Many different ways to do this! Your final answer should be an integer.
# MAKE SURE TO READ THE FULL INSTRUCTIONS ABOVE CAREFULLY, AS THE EVALUATION SCRIPT IS VERY STRICT.
# Link to Solution: https://gist.github.com/Pierian-Data/ea3121efac5dd3338c280ff10068f9c8

import numpy as np
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])
total_rolls_over_two = dice_rolls[dice_rolls > 2].shape[0]

In [184]:
a1 = np.arange(0, 10)
a2 = np.arange(10, 0, -1)
a2

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [185]:
a1 + a2

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [187]:
a1 - a2

array([-10,  -8,  -6,  -4,  -2,   0,   2,   4,   6,   8])

In [190]:
a1.mean()

4.5

In [197]:
a1.var()

8.25

In [198]:
array2d = np.arange(0, 25).reshape((5,5))
array2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [199]:
type(array2d)

numpy.ndarray

In [200]:
array2d.sum()

300

In [202]:
# Sums up value in all the columns.
array2d.sum(axis = 0)

array([50, 55, 60, 65, 70])

In [204]:
# Sums up values in all the rows.
array2d.sum(axis = 1)

array([ 10,  35,  60,  85, 110])

In [205]:
# TASK: Use numpy to check the total remaining in the account after the series of transactions.
# NOTE: Many different ways to do this! 
# MAKE SURE TO READ THE FULL INSTRUCTIONS ABOVE CAREFULLY, AS THE EVALUATION SCRIPT IS VERY STRICT.
# Link to Solution: https://gist.github.com/Pierian-Data/225a449484e12e0535fbbac2231b426b

import numpy as np
account_transactions = np.array([100,-200,300,-400,100,100,-230,450,500,2000])
account_total = account_transactions.sum()