In [13]:
import numpy as np

In [14]:
multi_array = [[1,2,3],[4,5,6],[7,8,9]]
multi_array

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [15]:
matrix = np.array(multi_array)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
type(matrix)

numpy.ndarray

In [17]:
np.arange(5, 25, 2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [18]:
# Rows x Columns
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.linspace(0, 23, num=4)

array([ 0.        ,  7.66666667, 15.33333333, 23.        ])

In [20]:
np.linspace(1, 12, 13)

array([ 1.        ,  1.91666667,  2.83333333,  3.75      ,  4.66666667,
        5.58333333,  6.5       ,  7.41666667,  8.33333333,  9.25      ,
       10.16666667, 11.08333333, 12.        ])

In [21]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
# Random number [0.0, 1.0)
np.random.rand(2,3,4)

array([[[0.42863072, 0.68652679, 0.98974017, 0.44556972],
        [0.55912742, 0.46442086, 0.82638501, 0.3966144 ],
        [0.32029616, 0.86076182, 0.27177446, 0.03950455]],

       [[0.34483421, 0.78829405, 0.76996717, 0.21298773],
        [0.45787436, 0.97500856, 0.40529134, 0.18944062],
        [0.28533848, 0.48949573, 0.34991613, 0.28597912]]])

In [27]:
# Standard normal distribution - mean = 0, variance = 1
np.random.randn(2,3,4)

array([[[-1.08501322,  0.72278873, -0.92391209,  0.9953188 ],
        [-0.24176372, -1.45890246, -0.49946146, -1.52093065],
        [ 0.01582377,  0.26886872,  0.04422925,  0.69888417]],

       [[ 0.50463998,  0.64362443,  0.71246232,  1.09954711],
        [-0.93589275, -1.02951276,  0.41108086,  0.20778091],
        [ 0.55802491, -0.49061808,  0.17283192,  1.03219601]]])

In [45]:
np.random.randint(5, 10, size=(2,3,4))

array([[[9, 6, 8, 6],
        [5, 9, 8, 8],
        [9, 6, 7, 6]],

       [[9, 8, 9, 9],
        [9, 5, 9, 5],
        [5, 8, 5, 7]]])

In [47]:
# hitchhiker's guide to the galaxy -> 42
np.random.seed(42)
np.random.rand(5)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [51]:
np.random.seed(42)
array = np.random.rand(25)
array

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258,
       0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497,
       0.18340451, 0.30424224, 0.52475643, 0.43194502, 0.29122914,
       0.61185289, 0.13949386, 0.29214465, 0.36636184, 0.45606998])

In [60]:
two_d_array = array.reshape(5, 5)
two_d_array

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864],
       [0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258],
       [0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497],
       [0.18340451, 0.30424224, 0.52475643, 0.43194502, 0.29122914],
       [0.61185289, 0.13949386, 0.29214465, 0.36636184, 0.45606998]])

In [54]:
array.min()

0.020584494295802447

In [57]:
array.argmin()

10

In [58]:
array.dtype

dtype('float64')

In [63]:
# (25,) to distingush from (1,25)
array.shape

(25,)

In [64]:
two_d_array.shape

(5, 5)

Coding Exercise Check-In: Creating NumPy Array

In [67]:
# TASK: Create a numpy array called myarray which consists of 101 evenly linearly spaced points between 0 and 10.
# MAKE SURE TO READ THE FULL INSTRUCTIONS ABOVE CAREFULLY, AS THE EVALUATION SCRIPT IS VERY STRICT.
# Link to Solution: https://gist.github.com/Pierian-Data/ea9c4d2fc6c98ac74af18134cd924867
# 
import numpy as np
myarray = np.linspace(0, 10, num=101)
myarray

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [69]:
# range
range = np.arange(0, 10)
range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
range[3]

3

In [71]:
range[3:6]

array([3, 4, 5])

In [72]:
range[:5]

array([0, 1, 2, 3, 4])

In [73]:
range[5:]

array([5, 6, 7, 8, 9])

In [74]:
range[:3] = 30
range

array([30, 30, 30,  3,  4,  5,  6,  7,  8,  9])

In [77]:
slice = range[:4]
slice

array([30, 30, 30,  3])

In [78]:
slice[:] = 400
slice

array([400, 400, 400, 400])

In [80]:
# NumPy Broadcasting in Action
range

array([400, 400, 400, 400,   4,   5,   6,   7,   8,   9])

In [82]:
copy = range.copy()
copy[:] = 5000

In [83]:
copy

array([5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000])

In [84]:
range

array([400, 400, 400, 400,   4,   5,   6,   7,   8,   9])