In [5]:
import numpy as np

In [18]:
multi_array = [[1,2,3],[4,5,6],[7,8,9]]
multi_array

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [19]:
matrix = np.array(multi_array)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
type(matrix)

numpy.ndarray

In [23]:
np.arange(5, 25, 2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [26]:
# Rows x Columns
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
np.linspace(0, 23, num=4)

array([ 0.        ,  7.66666667, 15.33333333, 23.        ])

In [29]:
np.linspace(1, 12, 13)

array([ 1.        ,  1.91666667,  2.83333333,  3.75      ,  4.66666667,
        5.58333333,  6.5       ,  7.41666667,  8.33333333,  9.25      ,
       10.16666667, 11.08333333, 12.        ])

In [30]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])