In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('./notebooks_final/08-Linear-Regression-Models/Advertising.csv')
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [3]:
X = df.drop('sales', axis=1)
y = df['sales']

In [4]:
from sklearn.preprocessing import PolynomialFeatures
polynomial_converter = PolynomialFeatures(degree=3, include_bias=False)
poly_features = polynomial_converter.fit_transform(X)
poly_features.shape

(200, 19)

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.3, random_state=101)
X_train.shape

(140, 19)

In [6]:
# Scale the data
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

StandardScaler()

In [7]:
scaled_X_train = scaler.transform(X_train)
scaled_X_test = scaler.transform(X_test)

In [8]:
X_train[0]

array([1.93200000e+02, 1.84000000e+01, 6.57000000e+01, 3.73262400e+04,
       3.55488000e+03, 1.26932400e+04, 3.38560000e+02, 1.20888000e+03,
       4.31649000e+03, 7.21142957e+06, 6.86802816e+05, 2.45233397e+06,
       6.54097920e+04, 2.33555616e+05, 8.33945868e+05, 6.22950400e+03,
       2.22433920e+04, 7.94234160e+04, 2.83593393e+05])

In [9]:
scaled_X_train[0]

array([ 0.49300171, -0.33994238,  1.61586707,  0.28407363, -0.02568776,
        1.49677566, -0.59023161,  0.41659155,  1.6137853 ,  0.08057172,
       -0.05392229,  1.01524393, -0.36986163,  0.52457967,  1.48737034,
       -0.66096022, -0.16360242,  0.54694754,  1.37075536])

# Ridge Regression


In [10]:
from sklearn.linear_model import Ridge
#help(ridge)
ridge_model = Ridge(alpha=10)
ridge_model.fit(scaled_X_train, y_train)

Ridge(alpha=10)

In [11]:
test_predictions = ridge_model.predict(scaled_X_test)

In [12]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
MAE = mean_absolute_error(y_test, test_predictions)
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))
RMSE

0.8946386461319672

In [13]:
from sklearn.linear_model import RidgeCV
ridge_cv_model = RidgeCV(alphas=(0.001, 0.005, 0.01, 0.05, 0.1, 1.0, 10.0), scoring='neg_mean_absolute_error')
ridge_cv_model.fit(scaled_X_train, y_train)

RidgeCV(alphas=array([1.e-03, 5.e-03, 1.e-02, 5.e-02, 1.e-01, 1.e+00, 1.e+01]),
        scoring='neg_mean_absolute_error')

In [14]:
ridge_cv_model.alpha_

0.05

In [15]:
from sklearn.metrics import SCORERS
SCORERS.keys()

dict_keys(['explained_variance', 'r2', 'max_error', 'neg_median_absolute_error', 'neg_mean_absolute_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_root_mean_squared_error', 'neg_mean_poisson_deviance', 'neg_mean_gamma_deviance', 'accuracy', 'roc_auc', 'roc_auc_ovr', 'roc_auc_ovo', 'roc_auc_ovr_weighted', 'roc_auc_ovo_weighted', 'balanced_accuracy', 'average_precision', 'neg_log_loss', 'neg_brier_score', 'adjusted_rand_score', 'homogeneity_score', 'completeness_score', 'v_measure_score', 'mutual_info_score', 'adjusted_mutual_info_score', 'normalized_mutual_info_score', 'fowlkes_mallows_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'jaccard', 'jaccard_macro', 'jaccard_micro', 'jaccard_samples', 'jaccard_weighted'])

In [16]:
test_predictions = ridge_cv_model.predict(scaled_X_test)

In [17]:
MAE = mean_absolute_error(y_test, test_predictions)
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))
RMSE

0.5982211275186771

In [18]:
ridge_cv_model.coef_

array([ 6.06478406,  0.55184154,  0.36889817, -7.74581672,  4.84782517,
       -1.42502383, -1.25852047,  0.66203443,  0.07144344,  3.4625185 ,
       -1.48218343,  1.13308409,  0.58651702, -0.28743776,  0.11965896,
        0.58981696, -0.25595451, -0.11983827, -0.13869641])

In [19]:
ridge_cv_model.best_score_

-0.3615767334739634

# LASSO - Least Absolute Shrinkage and Selection Operator

In [20]:
from sklearn.linear_model import LassoCV
lasso_cv_model = LassoCV(eps=0.1, n_alphas=(100), cv=5)
lasso_cv_model.fit(scaled_X_train, y_train)

LassoCV(cv=5, eps=0.1)

In [21]:
lasso_cv_model.alpha_

0.49430709092258285

In [22]:
test_predictions = lasso_cv_model.predict(scaled_X_test)
test_predictions

array([13.45338009, 19.25419883, 11.92693647, 15.65984482,  9.59275546,
        8.91555193, 20.13945651, 16.8940403 , 10.30392219, 19.35585759,
       10.53851739, 13.52523076, 11.84291254, 21.97446984, 18.50473737,
       10.18416558, 12.51310389,  9.62098689,  9.58916887, 20.90872394,
        9.01385339, 18.173473  , 27.16694718, 24.24589466,  9.88609246,
       11.41696271, 21.15799353,  9.85860773, 12.19996303,  9.4393254 ,
        9.57055425, 19.39654459, 10.68194027,  8.72638276, 17.22100511,
        9.65240517, 10.54721814,  9.97920093,  8.9632026 , 10.659277  ,
       11.98376175, 10.3246849 , 11.10752122,  9.02040466, 11.57917154,
       10.78030361,  8.57798137, 15.15282195, 12.72136342, 21.35302125,
       10.86548461, 12.78550905, 14.91137805, 11.70074134, 11.30228394,
        8.43176178, 24.92405026, 10.66203455, 17.58679446, 14.93460903])

In [23]:
MAE = mean_absolute_error(y_test, test_predictions)
MAE

0.6541723161252854

In [24]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))
RMSE

1.1308001022762533

In [25]:
lasso_cv_model.coef_

array([1.002651  , 0.        , 0.        , 0.        , 3.79745279,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        ])

# Elastic Net

In [32]:
from sklearn.linear_model import ElasticNetCV
elastic_cv_model = ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1.0], eps=0.001, n_alphas=100, max_iter=1000000)
elastic_cv_model.fit(scaled_X_train, y_train)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1.0], max_iter=1000000)

In [33]:
elastic_cv_model.l1_ratio_

1.0

In [34]:
elastic_cv_model.alpha_

0.004943070909225827

In [36]:
test_predictions = elastic_cv_model.predict(scaled_X_test)
test_predictions

array([14.16203485, 19.2942685 , 12.34178429, 16.97745571,  8.02340978,
        6.95799942, 20.11875833, 17.32880647, 10.43139937, 19.96174466,
        9.56959473, 13.94205676, 11.90851817, 23.35138146, 19.56656277,
        9.27838151, 12.30485359,  9.30152997,  8.56733436, 21.51633564,
        7.06650884, 19.3377222 , 27.28027149, 24.52239173,  9.17172464,
       11.60918126, 20.73841405,  9.29953525, 12.56948515,  8.40051066,
        8.56984613, 20.03587647, 10.83439653,  6.79505173, 18.18820331,
        9.48107219, 10.41803957,  9.70785725,  7.22932328, 10.85467692,
       12.85491418, 10.51648453, 11.26905127,  7.41516944, 11.54705407,
       10.42233031,  6.02782344, 15.36338733, 13.18723611, 22.67619584,
       10.4721906 , 13.01165791, 14.56684361, 11.90062303, 11.47303307,
        5.59404766, 25.06115365,  9.69468957, 17.44771723, 15.60375637])

In [37]:
MAE = mean_absolute_error(y_test, test_predictions)
MAE

0.43350346185900707

In [38]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))
RMSE

0.6063140748984027